# Based on https://gist.github.com/domenic/ec8b0fc8ab45f39403dd
name: Build Docs
permissions:
  contents: write
on:
  pull_request:
    branches:
    - main
  push:
    branches:
    - main
jobs:
  build:
    name: Build docs
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        path: lk3d

    - name: Setup Lua
      uses: leafo/gh-actions-lua@v8
      with:
        luaVersion: 5.4

    - name: Setup Lua Rocks
      uses: leafo/gh-actions-luarocks@v4

    - name: Pull LDoc
      uses: actions/checkout@v3
      with:
        repository: impulsh/LDoc
        path: ldoc
    
    - name: Build LDoc
      working-directory: ldoc
      run: luarocks make


    - name: Build docs
      working-directory: lk3d
      run: ldoc .

    - name: Copy media
      working-directory: lk3d
      run: |
        mkdir docs/html/images
        cp -rv docs/images/* docs/html/images

    - name: Deploy
      if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: lk3d/docs/html
